### ISSUE TITLE
Change token image when flying

### ISSUE THREAD

**Issue by JacobSeibel-TransLoc** [LeafWulf/flying-tokens#4]
I have a player with a bird familiar, and it would be awesome to have a version of the token with wings folded when not flying and a version with the wings spread when flying.

Is it possible to have the effect also change the image? I understand this would probably involve adding a field to the token configuration for the "flying" version of the image.

**Comment by roi007leaf** [comment]
This should already be available, pick a flying token on the token settings

**Comment by JacobSeibel-TransLoc** [comment]
Ah, sorry I didn't see it in the readme! Excellent! Thanks!
